# Generated by Django 2.1.5 on 2019-02-06 23:48

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('descricao', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Conteúdo')),
                ('imagem', models.ImageField(blank=True, default='', null=True, upload_to='foto/post', verbose_name='Foto')),
            ],
        ),
    ]
