# Generated by Django 2.1.5 on 2019-01-30 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='data_criada',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='data_publicacao',
            new_name='published_date',
        ),
    ]
