# Generated by Django 2.1.5 on 2019-02-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_criado'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sumario',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Escreva o conteúdo no máximo 150 caracteres'),
        ),
    ]
