# Generated by Django 2.1.5 on 2019-02-05 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capitulo_jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
            ],
        ),
        migrations.AddField(
            model_name='capitulo_jogo',
            name='chave_estrangeira',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Jogo', verbose_name='jogo'),
        ),
    ]
