# Generated by Django 2.1.5 on 2019-02-05 22:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogo',
            name='descricao',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Conteúdo'),
        ),
    ]
