# Generated by Django 2.1.5 on 2019-02-12 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='nome')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('intervalo', models.IntegerField(blank=True, default=4500, null=True, verbose_name='Digite o intervalo em que o banner irá deslizar em milisegundos')),
                ('ocultartitulo', models.BooleanField(default=False, verbose_name='Marque para ocultar o título do banner')),
                ('chave_estrangeira_jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Jogo')),
            ],
        ),
    ]
